apiVersion: apps/v1 # for versions before 1.9.0 use apps/v1beta2 
kind: Deployment 
metadata: 
  name: hellowebapp-deployment 
spec: 
  selector: 
    matchLabels: 
      app: hellowebapp 
  replicas: 5 # tells deployment to run 2 pods matching the template 
  template:
    metadata: 
      labels: 
        app: hellowebapp 
    spec: 
      containers: 
      - name: hellowebapp 
        image: spparida/hellowebapp
        ports: 
        - containerPort: 80 
--- 
# https://kubernetes.io/docs/concepts/services-networking/service/#defining-a-service  
kind: Service 
apiVersion: v1 
metadata: 
  name: hellowebapp 
spec: 
  selector: 
    app: hellowebapp 
  ports: 
  - protocol: TCP 
    port: 80
    targetPort: 80 
  type: LoadBalancer 

